# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python -m unittest discover
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6377"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30